### ISSUE TITLE
enigma2 resolution

### ISSUE THREAD

**Issue by 0x13A0F** [technic/enigma2_example#4]
Hello,

First i'd like to thank you for this amazing contribution, it really helped me.
I have a question concerning enigma2 itself, do u have any idea how to set the resolution as full hd for example,
because all plugins looks good on VNC, but then when i test them on a real receiver, everything is so small.

**Comment by technic** [comment]
Hi,

Add the following to docker-compose.yml
```
    environment:
      - RESOLUTION=1920x1080x16
```
This is used by startup script as an argument to xvfb.

Select FullHD screen in enigma2 settings. You need to add this skin to container first, see [here](https://github.com/technic/iptvdream4x/blob/cd76a78d5b6eb3c4103c1eea0018530582afd59e/vm-docker/Dockerfile#L3).

After docker rebuild and restart it should work.

Note the gstreamer-SDL renderer (I might have coded it in the non-optimal way) will eat much more CPU for 1080p image.

**Comment by 0x13A0F** [comment]
Hi,

Thank you for the fast response,
I tested it, it's working exactly as i wanted it.

Here is what i added in my Dockerfile:
```
RUN  rev="acac722e25a5e2d69d60d4df6bcef701049e2b38" \
    && curl -fsSL https://github.com/littlesat/skin-PLiHD/archive/$rev.zip -o skin-PLiHD.zip \
    && unzip skin-PLiHD.zip && cd skin-PLiHD-$rev && cp -arv . / \
    && echo 'config.skin.primary_skin=PLi-FullHD/skin.xml' >> /etc/enigma2/settings
```

Thank you for your help

**Comment by 0x13A0F** [comment]
If you don't mind, i have another issue,

It's with vscode, i followed exactly what you said, but auto completion is not working, i googled a bit and found it was a. Issue with the new version of vscode, 

apparently pylance is no longer accepting env file in .env, i even tried adding extraPaths in vscode settings.
Do you have any idea how to make it work ?
