### ISSUE TITLE
autocompletion in the new vscode

### ISSUE THREAD

**Issue by technic** [technic/enigma2_example#5]
If you don't mind, i have another issue,

It's with vscode, i followed exactly what you said, but auto completion is not working, i googled a bit and found it was a. Issue with the new version of vscode, 

apparently pylance is no longer accepting env file in .env, i even tried adding extraPaths in vscode settings.
Do you have any idea how to make it work ?

_Originally posted by @0x13A0F in https://github.com/technic/enigma2_example/issues/4#issuecomment-879021443_

**Comment by technic** [comment]
Hi, for me it works. The vscode issue tracker also says, that it is fixed.
You can also try to set both `python.analysis.extraPaths` and `python.autoComplete.extraPaths` in the settings.json - I think I had this some time ago.

Also, Pylance will complain about some of the python2 code.

cc: @0x13A0F

**Comment by 0x13A0F** [comment]
Surprisingly now it works ! i have tried everything
i already tried `python.analysis.extraPaths` and i also tried `python.autoComplete.extraPaths`
but never thought to try them both x)
Thanks
