### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by mtester270** [technic/enigma2_example#6]
Hi, how can I:

1) connect with ssh/telnet such as on classic E2 box?

2) install python site-packages such as requests, ... and other necessary libraries for me

**Comment by technic** [comment]
1. you can use `docker exec -it enigma2 bash` - here `enigma2` is container name.
2. after you get to the shell you can install things normally.

**Comment by technic** [comment]
and if you want installed packages to be saved to docker image (i.e. they will persist upon container restart) you should add corresponding commands to Dockerfile.

**Comment by mtester270** [comment]
Thanks, do you have some donation ?
